const data = {
    continents: [
        { id: 1, name: "Africa", code: "AF" },
        { id: 2, name: "Antarctica", code: "AN" },
        { id: 3, name: "Asia", code: "AS" },
        { id: 4, name: "Europe", code: "EU" },
        { id: 5, name: "North America", code: "NA" },
        { id: 6, name: "Oceania", code: "OC" },
        { id: 7, name: "South America", code: "SA" }
    ],
    languages: [
        { name: "Abkhazian", code: "ab", native: "аҧсуа бызшәа", rtl: false, countryCodes: ["GE", "RU"] },
        { name: "Afar", code: "aa", native: "Afaraf", rtl: false, countryCodes: ["DJ", "ER", "ET"] },
        { name: "Afrikaans", code: "af", native: "Afrikaans", rtl: false, countryCodes: ["ZA"] },
        { name: "Akan", code: "ak", native: "Akan", rtl: false, countryCodes: ["GH"] },
        { name: "Albanian", code: "sq", native: "Shqip", rtl: false, countryCodes: ["AL", "XK", "MK", "ME", "RS"] },
        { name: "Amharic", code: "am", native: "አማርኛ", rtl: false, countryCodes: ["ET"] },
        { name: "Arabic", code: "ar", native: "العربية", rtl: true, countryCodes: ["AE", "BH", "DJ", "DZ", "EG", "EH", "ER", "IL", "IQ", "JO", "KM", "KW", "LB", "LY", "MA", "MR", "OM", "PS", "QA", "SA", "SD", "SO", "SS", "SY", "TD", "TN", "YE"] },
        { name: "Aragonese", code: "an", native: "aragonés", rtl: false, countryCodes: ["ES"] },
        { name: "Armenian", code: "hy", native: "Հայերեն", rtl: false, countryCodes: ["AM"] },
        { name: "Assamese", code: "as", native: "অসমীয়া", rtl: false, countryCodes: ["IN"] },
        { name: "Avaric", code: "av", native: "авар мацӀ", rtl: false, countryCodes: ["RU"] },
        { name: "Avestan", code: "ae", native: "avesta", rtl: false, countryCodes: ["IR"] },
        { name: "Aymara", code: "ay", native: "aymar aru", rtl: false, countryCodes: ["BO", "PE"] },
        { name: "Azerbaijani", code: "az", native: "azərbaycan dili", rtl: false, countryCodes: ["AZ"] },
        { name: "Bambara", code: "bm", native: "bamanankan", rtl: false, countryCodes: ["ML"] },
        { name: "Bashkir", code: "ba", native: "башҡорт теле", rtl: false, countryCodes: ["RU"] },
        { name: "Basque", code: "eu", native: "euskara", rtl: false, countryCodes: ["ES", "FR"] },
        { name: "Belarusian", code: "be", native: "беларуская мова", rtl: false, countryCodes: ["BY"] },
        { name: "Bengali", code: "bn", native: "বাংলা", rtl: false, countryCodes: ["BD", "IN"] },
        { name: "Bihari", code: "bh", native: "भोजपुरी", rtl: false, countryCodes: ["IN"] },
        { name: "Bislama", code: "bi", native: "Bislama", rtl: false, countryCodes: ["VU"] },
        { name: "Bosnian", code: "bs", native: "bosanski jezik", rtl: false, countryCodes: ["BA", "HR", "ME", "RS"] },
        { name: "Breton", code: "br", native: "brezhoneg", rtl: false, countryCodes: ["FR"] },
        { name: "Bulgarian", code: "bg", native: "български език", rtl: false, countryCodes: ["BG"] },
        { name: "Burmese", code: "my", native: "ဗမာစာ", rtl: false, countryCodes: ["MM"] },
        { name: "Catalan; Valencian", code: "ca", native: "Català", rtl: false, countryCodes: ["AD", "ES", "FR", "IT"] },
        { name: "Chamorro", code: "ch", native: "Chamoru", rtl: false, countryCodes: ["GU"] },
        { name: "Chechen", code: "ce", native: "нохчийн мотт", rtl: false, countryCodes: ["RU"] },
        { name: "Chichewa; Chewa; Nyanja", code: "ny", native: "chiCheŵa", rtl: false, countryCodes: ["MW"] },
        { name: "Chinese", code: "zh", native: "中文 (Zhōngwén)", rtl: false, countryCodes: ["CN", "HK", "MO", "SG", "TW"] },
        { name: "Chuvash", code: "cv", native: "чӑваш чӗлхи", rtl: false, countryCodes: ["RU"] },
        { name: "Cornish", code: "kw", native: "Kernewek", rtl: false, countryCodes: ["GB"] },
        { name: "Corsican", code: "co", native: "corsu", rtl: false, countryCodes: ["FR", "IT"] },
        { name: "Cree", code: "cr", native: "ᓀᐦᐃᔭᐍᐏᐣ", rtl: false, countryCodes: ["CA"] },
        { name: "Croatian", code: "hr", native: "hrvatski jezik", rtl: false, countryCodes: ["HR", "BA", "ME", "RS"] },
        { name: "Czech", code: "cs", native: "čeština", rtl: false, countryCodes: ["CZ"] },
        { name: "Danish", code: "da", native: "dansk", rtl: false, countryCodes: ["DK"] },
        { name: "Divehi; Dhivehi; Maldivian;", code: "dv", native: "ދިވެހި", rtl: true, countryCodes: ["MV"] },
        { name: "Dutch", code: "nl", native: "Nederlands", rtl: false, countryCodes: ["NL", "BE"] },
        { name: "English", code: "en", native: "English", rtl: false, countryCodes: ["AU", "CA", "GB", "IN", "NZ", "PH", "US", "ZA"] },
        { name: "Esperanto", code: "eo", native: "Esperanto", rtl: false, countryCodes: [] },
        { name: "Estonian", code: "et", native: "eesti", rtl: false, countryCodes: ["EE"] },
        { name: "Ewe", code: "ee", native: "Eʋegbe", rtl: false, countryCodes: ["GH", "TG"] },
        { name: "Faroese", code: "fo", native: "føroyskt", rtl: false, countryCodes: ["FO"] },
        { name: "Fijian", code: "fj", native: "vosa Vakaviti", rtl: false, countryCodes: ["FJ"] },
        { name: "Finnish", code: "fi", native: "suomi", rtl: false, countryCodes: ["FI"] },
        { name: "French", code: "fr", native: "français", rtl: false, countryCodes: ["FR", "BE", "CA", "CH", "LU"] },
        { name: "Fula; Fulah; Pulaar; Pular", code: "ff", native: "Fulfulde", rtl: false, countryCodes: ["SN"] },
        { name: "Galician", code: "gl", native: "Galego", rtl: false, countryCodes: ["ES"] },
        { name: "Georgian", code: "ka", native: "ქართული", rtl: false, countryCodes: ["GE"] },
        { name: "German", code: "de", native: "Deutsch", rtl: false, countryCodes: ["DE", "AT", "CH", "LI", "LU"] },
        { name: "Greek, Modern", code: "el", native: "ελληνικά", rtl: false, countryCodes: ["GR", "CY"] },
        { name: "Guaraní", code: "gn", native: "Avañe'ẽ", rtl: false, countryCodes: ["PY"] },
        { name: "Gujarati", code: "gu", native: "ગુજરાતી", rtl: false, countryCodes: ["IN"] },
        { name: "Haitian; Haitian Creole", code: "ht", native: "Kreyòl ayisyen", rtl: false, countryCodes: ["HT"] },
        { name: "Hausa", code: "ha", native: "Hausa, هَوُسَ", rtl: false, countryCodes: ["NG"] },
        { name: "Hebrew (modern)", code: "he", native: "עברית", rtl: true, countryCodes: ["IL"] },
        { name: "Herero", code: "hz", native: "Otjiherero", rtl: false, countryCodes: ["NA"] },
        { name: "Hindi", code: "hi", native: "हिन्दी, हिंदी", rtl: false, countryCodes: ["IN"] },
        { name: "Hiri Motu", code: "ho", native: "Hiri Motu", rtl: false, countryCodes: ["PG"] },
        { name: "Hungarian", code: "hu", native: "magyar", rtl: false, countryCodes: ["HU"] },
        { name: "Interlingua", code: "ia", native: "Interlingua", rtl: false, countryCodes: [] },
        { name: "Indonesian", code: "id", native: "Bahasa Indonesia", rtl: false, countryCodes: ["ID"] },
        { name: "Interlingue", code: "ie", native: "Originally called Occidental; then Interlingue after WWII", rtl: false, countryCodes: [] },
        { name: "Irish", code: "ga", native: "Gaeilge", rtl: false, countryCodes: ["IE"] },
        { name: "Igbo", code: "ig", native: "Asụsụ Igbo", rtl: false, countryCodes: ["NG"] },
        { name: "Inupiaq", code: "ik", native: "Iñupiaq, Iñupiatun", rtl: false, countryCodes: ["US"] },
        { name: "Ido", code: "io", native: "Ido", rtl: false, countryCodes: [] },
        { name: "Icelandic", code: "is", native: "Íslenska", rtl: false, countryCodes: ["IS"] },
        { name: "Italian", code: "it", native: "Italiano", rtl: false, countryCodes: ["IT", "CH"] },
        { name: "Inuktitut", code: "iu", native: "ᐃᓄᒃᑎᑐᑦ", rtl: false, countryCodes: ["CA"] },
        { name: "Japanese", code: "ja", native: "日本語 (にほんご)", rtl: false, countryCodes: ["JP"] },
        { name: "Javanese", code: "jv", native: "ꦧꦱꦗꦮ, Basa Jawa", rtl: false, countryCodes: ["ID"] },
        { name: "Kalaallisut, Greenlandic", code: "kl", native: "kalaallisut, kalaallit oqaasii", rtl: false, countryCodes: ["GL"] },
        { name: "Kannada", code: "kn", native: "ಕನ್ನಡ", rtl: false, countryCodes: ["IN"] },
        { name: "Kanuri", code: "kr", native: "Kanuri", rtl: false, countryCodes: ["NG"] },
        { name: "Kashmiri", code: "ks", native: "कश्मीरी, كشميري‎", rtl: false, countryCodes: ["IN"] },
        { name: "Kazakh", code: "kk", native: "қазақ тілі", rtl: false, countryCodes: ["KZ"] },
        { name: "Khmer", code: "km", native: "ខ្មែរ", rtl: false, countryCodes: ["KH"] },
        { name: "Kikuyu, Gikuyu", code: "ki", native: "Gĩkũyũ", rtl: false, countryCodes: ["KE"] },
        { name: "Kinyarwanda", code: "rw", native: "Ikinyarwanda", rtl: false, countryCodes: ["RW"] },
        { name: "Kyrgyz", code: "ky", native: "Кыргызча, Кыргыз тили", rtl: false, countryCodes: ["KG"] },
        { name: "Komi", code: "kv", native: "коми кыв", rtl: false, countryCodes: ["RU"] },
        { name: "Kongo", code: "kg", native: "KiKongo", rtl: false, countryCodes: ["CG"] },
        { name: "Korean", code: "ko", native: "한국어 (韓國語), 조선말 (朝鮮語)", rtl: false, countryCodes: ["KR", "KP"] },
        { name: "Kurdish", code: "ku", native: "Kurdî, كوردی‎", rtl: true, countryCodes: ["TR", "IQ", "IR", "SY"] },
        { name: "Kwanyama, Kuanyama", code: "kj", native: "Kuanyama", rtl: false, countryCodes: ["AO"] },
        { name: "Latin", code: "la", native: "latine, lingua latina", rtl: false, countryCodes: [] },
        { name: "Luxembourgish, Letzeburgesch", code: "lb", native: "Lëtzebuergesch", rtl: false, countryCodes: ["LU"] },
        { name: "Ganda", code: "lg", native: "Luganda", rtl: false, countryCodes: ["UG"] },
        { name: "Limburgish, Limburgan, Limburger", code: "li", native: "Limburgs", rtl: false, countryCodes: ["NL", "BE", "DE"] },
        { name: "Lingala", code: "ln", native: "Lingála", rtl: false, countryCodes: ["CD"] },
        { name: "Lao", code: "lo", native: "ພາສາລາວ", rtl: false, countryCodes: ["LA"] },
        { name: "Lithuanian", code: "lt", native: "lietuvių kalba", rtl: false, countryCodes: ["LT"] },
        { name: "Luba-Katanga", code: "lu", native: "", rtl: false, countryCodes: ["CD"] },
        { name: "Latvian", code: "lv", native: "latviešu valoda", rtl: false, countryCodes: ["LV"] },
        { name: "Manx", code: "gv", native: "Gaelg, Gailck", rtl: false, countryCodes: ["IM"] },
        { name: "Macedonian", code: "mk", native: "македонски јазик", rtl: false, countryCodes: ["MK"] },
        { name: "Malagasy", code: "mg", native: "fiteny malagasy", rtl: false, countryCodes: ["MG"] },
        { name: "Malay", code: "ms", native: "Bahasa Melayu, بهاس ملايو‎", rtl: false, countryCodes: ["MY"] },
        { name: "Malayalam", code: "ml", native: "മലയാളം", rtl: false, countryCodes: ["IN"] },
        { name: "Maltese", code: "mt", native: "Malti", rtl: false, countryCodes: ["MT"] },
        { name: "Māori", code: "mi", native: "te reo Māori", rtl: false, countryCodes: ["NZ"] },
        { name: "Marathi (Marāṭhī)", code: "mr", native: "मराठी", rtl: false, countryCodes: ["IN"] },
        { name: "Marshallese", code: "mh", native: "Kajin M̧ajeļ", rtl: false, countryCodes: ["MH"] },
        { name: "Mongolian", code: "mn", native: "Монгол хэл", rtl: false, countryCodes: ["MN"] },
        { name: "Nauru", code: "na", native: "Ekakairũ Naoero", rtl: false, countryCodes: ["NR"] },
        { name: "Navajo, Navaho", code: "nv", native: "Diné bizaad, Dinékʼehǰí", rtl: false, countryCodes: ["US"] },
        { name: "Norwegian Bokmål", code: "nb", native: "Norsk bokmål", rtl: false, countryCodes: ["NO"] },
        { name: "North Ndebele", code: "nd", native: "isiNdebele", rtl: false, countryCodes: ["ZW"] },
        { name: "Nepali", code: "ne", native: "नेपाली", rtl: false, countryCodes: ["NP"] },
        { name: "Ndonga", code: "ng", native: "Owambo", rtl: false, countryCodes: ["NA"] },
        { name: "Norwegian Nynorsk", code: "nn", native: "Norsk nynorsk", rtl: false, countryCodes: ["NO"] },
        { name: "Norwegian", code: "no", native: "Norsk", rtl: false, countryCodes: ["NO"] },
        { name: "Sichuan Yi, Nuosu", code: "ii", native: "ꆈꌠ꒿ Nuosuhxop", rtl: false, countryCodes: ["CN"] },
        { name: "South Ndebele", code: "nr", native: "isiNdebele", rtl: false, countryCodes: ["ZA"] },
        { name: "Occitan", code: "oc", native: "occitan, lenga d'òc", rtl: false, countryCodes: ["FR"] },
        { name: "Ojibwe, Ojibwa", code: "oj", native: "ᐊᓂᔑᓈᐯᒧᐎᓐ", rtl: false, countryCodes: ["CA"] },
        { name: "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic", code: "cu", native: "ѩзыкъ словѣньскъ", rtl: false, countryCodes: [] },
        { name: "Oromo", code: "om", native: "Afaan Oromoo", rtl: false, countryCodes: ["ET"] },
        { name: "Oriya", code: "or", native: "ଓଡ଼ିଆ", rtl: false, countryCodes: ["IN"] },
        { name: "Ossetian, Ossetic", code: "os", native: "ирон æвзаг", rtl: false, countryCodes: ["RU", "GE"] },
        { name: "Panjabi, Punjabi", code: "pa", native: "ਪੰਜਾਬੀ, پنجابی‎", rtl: false, countryCodes: ["IN", "PK"] },
        { name: "Pāli", code: "pi", native: "पाऴि", rtl: false, countryCodes: [] },
        { name: "Persian", code: "fa", native: "فارسی", rtl: true, countryCodes: ["IR", "AF", "TJ", "UZ"] },
        { name: "Polish", code: "pl", native: "język polski, polszczyzna", rtl: false, countryCodes: ["PL"] },
        { name: "Pashto, Pushto", code: "ps", native: "پښتو", rtl: true, countryCodes: ["AF", "PK"] },
        { name: "Portuguese", code: "pt", native: "Português", rtl: false, countryCodes: ["PT", "BR"] },
        { name: "Quechua", code: "qu", native: "Runa Simi, Kichwa", rtl: false, countryCodes: ["PE"] },
        { name: "Romansh", code: "rm", native: "rumantsch grischun", rtl: false, countryCodes: ["CH"] },
        { name: "Kirundi", code: "rn", native: "Ikirundi", rtl: false, countryCodes: ["BI"] },
        { name: "Romanian, Moldavian, Moldovan", code: "ro", native: "Română", rtl: false, countryCodes: ["RO", "MD"] },
        { name: "Russian", code: "ru", native: "русский язык", rtl: false, countryCodes: ["RU", "BY", "KZ", "KG", "MD", "TJ", "TM", "UZ", "UA"] },
        { name: "Sanskrit (Saṁskṛta)", code: "sa", native: "संस्कृतम्", rtl: false, countryCodes: [] },
        { name: "Sardinian", code: "sc", native: "sardu", rtl: false, countryCodes: ["IT"] },
        { name: "Sindhi", code: "sd", native: "सिन्धी, سنڌي، سندھی‎", rtl: false, countryCodes: ["PK", "IN"] },
        { name: "Northern Sami", code: "se", native: "Davvisámegiella", rtl: false, countryCodes: ["NO", "SE", "FI", "RU"] },
        { name: "Samoan", code: "sm", native: "gagana fa'a Samoa", rtl: false, countryCodes: ["WS"] },
        { name: "Sango", code: "sg", native: "yângâ tî sängö", rtl: false, countryCodes: ["CF"] },
        { name: "Serbian", code: "sr", native: "српски језик", rtl: false, countryCodes: ["RS", "BA", "ME"] },
        { name: "Scottish Gaelic; Gaelic", code: "gd", native: "Gàidhlig", rtl: false, countryCodes: ["GB"] },
        { name: "Shona", code: "sn", native: "chiShona", rtl: false, countryCodes: ["ZW"] },
        { name: "Sinhala, Sinhalese", code: "si", native: "සිංහල", rtl: false, countryCodes: ["LK"] },
        { name: "Slovak", code: "sk", native: "slovenčina", rtl: false, countryCodes: ["SK"] },
        { name: "Slovene", code: "sl", native: "slovenščina", rtl: false, countryCodes: ["SI"] },
        { name: "Somali", code: "so", native: "Soomaaliga, af Soomaali", rtl: false, countryCodes: ["SO", "DJ"] },
        { name: "Southern Sotho", code: "st", native: "Sesotho", rtl: false, countryCodes: ["LS"] },
        { name: "Spanish; Castilian", code: "es", native: "Español, castellano", rtl: false, countryCodes: ["ES", "MX", "US"] },
        { name: "Sundanese", code: "su", native: "Basa Sunda", rtl: false, countryCodes: ["ID"] },
        { name: "Swahili", code: "sw", native: "Kiswahili", rtl: false, countryCodes: ["KE", "TZ", "UG"] },
        { name: "Swati", code: "ss", native: "SiSwati", rtl: false, countryCodes: ["SZ"] },
        { name: "Swedish", code: "sv", native: "svenska", rtl: false, countryCodes: ["SE"] },
        { name: "Tamil", code: "ta", native: "தமிழ்", rtl: false, countryCodes: ["IN", "LK", "MY", "SG"] },
        { name: "Telugu", code: "te", native: "తెలుగు", rtl: false, countryCodes: ["IN"] },
        { name: "Tajik", code: "tg", native: "тоҷикӣ, toçikī, تاجیکی‎", rtl: false, countryCodes: ["TJ"] },
        { name: "Thai", code: "th", native: "ไทย", rtl: false, countryCodes: ["TH"] },
        { name: "Tigrinya", code: "ti", native: "ትግርኛ", rtl: false, countryCodes: ["ER", "ET"] },
        { name: "Tibetan Standard, Tibetan, Central", code: "bo", native: "བོད་ཡིག", rtl: false, countryCodes: ["CN", "IN"] },
        { name: "Turkmen", code: "tk", native: "Türkmen, Түркмен", rtl: false, countryCodes: ["TM"] },
        { name: "Tagalog", code: "tl", native: "Wikang Tagalog", rtl: false, countryCodes: ["PH"] },
        { name: "Tswana", code: "tn", native: "Setswana", rtl: false, countryCodes: ["BW", "ZA"] },
        { name: "Tonga (Tonga Islands)", code: "to", native: "faka Tonga", rtl: false, countryCodes: ["TO"] },
        { name: "Turkish", code: "tr", native: "Türkçe", rtl: false, countryCodes: ["TR", "CY"] },
        { name: "Tsonga", code: "ts", native: "Xitsonga", rtl: false, countryCodes: ["ZA"] },
        { name: "Tatar", code: "tt", native: "татар теле, tatar tele", rtl: false, countryCodes: ["RU", "TJ"] },
        { name: "Twi", code: "tw", native: "Twi", rtl: false, countryCodes: ["GH"] },
        { name: "Tahitian", code: "ty", native: "Reo Tahiti", rtl: false, countryCodes: ["PF"] },
        { name: "Uighur, Uyghur", code: "ug", native: "ئۇيغۇرچە‎, Uyghurche", rtl: true, countryCodes: ["CN"] },
        { name: "Ukrainian", code: "uk", native: "українська мова", rtl: false, countryCodes: ["UA"] },
        { name: "Urdu", code: "ur", native: "اردو", rtl: true, countryCodes: ["PK", "IN"] },
        { name: "Uzbek", code: "uz", native: "Oʻzbek, Ўзбек, أۇزبېك‎", rtl: false, countryCodes: ["UZ", "AF"] },
        { name: "Venda", code: "ve", native: "Tshivenḓa", rtl: false, countryCodes: ["ZA"] },
        { name: "Vietnamese", code: "vi", native: "Tiếng Việt", rtl: false, countryCodes: ["VN"] },
        { name: "Volapük", code: "vo", native: "Volapük", rtl: false, countryCodes: [] },
        { name: "Walloon", code: "wa", native: "Walon", rtl: false, countryCodes: ["BE"] },
        { name: "Welsh", code: "cy", native: "Cymraeg", rtl: false, countryCodes: ["GB"] },
        { name: "Wolof", code: "wo", native: "Wollof", rtl: false, countryCodes: ["SN"] },
        { name: "Western Frisian", code: "fy", native: "Frysk", rtl: false, countryCodes: ["NL", "DE"] },
        { name: "Xhosa", code: "xh", native: "isiXhosa", rtl: false, countryCodes: ["ZA"] },
        { name: "Yiddish", code: "yi", native: "ייִדיש", rtl: true, countryCodes: ["DE", "IL", "US"] },
        { name: "Yoruba", code: "yo", native: "Yorùbá", rtl: false, countryCodes: ["NG", "BJ"] },
        { name: "Zhuang, Chuang", code: "za", native: "Saɯ cueŋƅ, Saw cuengh", rtl: false, countryCodes: ["CN"] },
        { name: "Zulu", code: "zu", native: "isiZulu", rtl: false, countryCodes: ["ZA"] }
    ],
    countries: [
        { name: "South Africa", code: "ZA", currency: "South African rand", native: "South Africa", phone: "27", continentId: "AF" },
        { name: "Nigeria", code: "NG", currency: "Nigerian naira", native: "Nigeria", phone: "234", continentId: "AF" },
        { name: "Egypt", code: "EG", currency: "Egyptian pound", native: "مصر‎", phone: "20", continentId: "AF" },
        { name: "Algeria", code: "DZ", currency: "Algerian dinar", native: "الجزائر", phone: "213", continentId: "AF" },
        { name: "Morocco", code: "MA", currency: "Moroccan dirham", native: "المغرب", phone: "212", continentId: "AF" },
        { name: "Kenya", code: "KE", currency: "Kenyan shilling", native: "Kenya", phone: "254", continentId: "AF" },
        { name: "Ethiopia", code: "ET", currency: "Ethiopian birr", native: "ኢትዮጵያ", phone: "251", continentId: "AF" },
        { name: "Ghana", code: "GH", currency: "Ghanaian cedi", native: "Ghana", phone: "233", continentId: "AF" },
        { name: "Tanzania", code: "TZ", currency: "Tanzanian shilling", native: "Tanzania", phone: "255", continentId: "AF" },
        { name: "Uganda", code: "UG", currency: "Ugandan shilling", native: "Uganda", phone: "256", continentId: "AF" },
        { name: "China", code: "CN", currency: "Chinese yuan", native: "中国", phone: "86", continentId: "AS" },
        { name: "India", code: "IN", currency: "Indian rupee", native: "भारत", phone: "91", continentId: "AS" },
        { name: "Japan", code: "JP", currency: "Japanese yen", native: "日本", phone: "81", continentId: "AS" },
        { name: "South Korea", code: "KR", currency: "South Korean won", native: "대한민국", phone: "82", continentId: "AS" },
        { name: "Saudi Arabia", code: "SA", currency: "Saudi riyal", native: "العربية السعودية", phone: "966", continentId: "AS" },
        { name: "Iran", code: "IR", currency: "Iranian rial", native: "ایران", phone: "98", continentId: "AS" },
        { name: "Turkey", code: "TR", currency: "Turkish lira", native: "Türkiye", phone: "90", continentId: "AS" },
        { name: "Indonesia", code: "ID", currency: "Indonesian rupiah", native: "Indonesia", phone: "62", continentId: "AS" },
        { name: "Pakistan", code: "PK", currency: "Pakistani rupee", native: "Pakistan", phone: "92", continentId: "AS" },
        { name: "Bangladesh", code: "BD", currency: "Bangladeshi taka", native: "Bangladesh", phone: "880", continentId: "AS" },
        { name: "Germany", code: "DE", currency: "Euro", native: "Deutschland", phone: "49", continentId: "EU" },
        { name: "United Kingdom", code: "GB", currency: "British pound", native: "United Kingdom", phone: "44", continentId: "EU" },
        { name: "France", code: "FR", currency: "Euro", native: "France", phone: "33", continentId: "EU" },
        { name: "Italy", code: "IT", currency: "Euro", native: "Italia", phone: "39", continentId: "EU" },
        { name: "Spain", code: "ES", currency: "Euro", native: "España", phone: "34", continentId: "EU" },
        { name: "Netherlands", code: "NL", currency: "Euro", native: "Nederland", phone: "31", continentId: "EU" },
        { name: "Switzerland", code: "CH", currency: "Swiss franc", native: "Schweiz", phone: "41", continentId: "EU" },
        { name: "Sweden", code: "SE", currency: "Swedish krona", native: "Sverige", phone: "46", continentId: "EU" },
        { name: "Belgium", code: "BE", currency: "Euro", native: "België", phone: "32", continentId: "EU" },
        { name: "Austria", code: "AT", currency: "Euro", native: "Österreich", phone: "43", continentId: "EU" },
        { name: "United States", code: "US", currency: "United States dollar", native: "United States", phone: "1", continentId: "NA" },
        { name: "Canada", code: "CA", currency: "Canadian dollar", native: "Canada", phone: "1", continentId: "NA" },
        { name: "Mexico", code: "MX", currency: "Mexican peso", native: "México", phone: "52", continentId: "NA" },
        { name: "Brazil", code: "BR", currency: "Brazilian real", native: "Brasil", phone: "55", continentId: "NA" },
        { name: "Colombia", code: "CO", currency: "Colombian peso", native: "Colombia", phone: "57", continentId: "NA" },
        { name: "Argentina", code: "AR", currency: "Argentine peso", native: "Argentina", phone: "54", continentId: "NA" },
        { name: "Chile", code: "CL", currency: "Chilean peso", native: "Chile", phone: "56", continentId: "NA" },
        { name: "Peru", code: "PE", currency: "Peruvian sol", native: "Perú", phone: "51", continentId: "NA" },
        { name: "Venezuela", code: "VE", currency: "Venezuelan bolívar", native: "Venezuela", phone: "58", continentId: "NA" },
        { name: "Ecuador", code: "EC", currency: "United States dollar", native: "Ecuador", phone: "593", continentId: "NA" },
        { name: "Australia", code: "AU", currency: "Australian dollar", native: "Australia", phone: "61", continentId: "OC" },
        { name: "Papua New Guinea", code: "PG", currency: "Papua New Guinean kina", native: "Papua Niugini", phone: "675", continentId: "OC" },
        { name: "New Zealand", code: "NZ", currency: "New Zealand dollar", native: "New Zealand", phone: "64", continentId: "OC" },
        { name: "Fiji", code: "FJ", currency: "Fijian dollar", native: "Fiji", phone: "679", continentId: "OC" },
        { name: "Solomon Islands", code: "SB", currency: "Solomon Islands dollar", native: "Solomon Islands", phone: "677", continentId: "OC" },
        { name: "Vanuatu", code: "VU", currency: "Vanuatu vatu", native: "Vanuatu", phone: "678", continentId: "OC" },
        { name: "Samoa", code: "WS", currency: "Samoan tālā", native: "Samoa", phone: "685", continentId: "OC" },
        { name: "Kiribati", code: "KI", currency: "Kiribati dollar", native: "Kiribati", phone: "686", continentId: "OC" },
        { name: "Tonga", code: "TO", currency: "Tongan paʻanga", native: "Tonga", phone: "676", continentId: "OC" },
        { name: "Federated States of Micronesia", code: "FM", currency: "United States dollar", native: "Micronesia", phone: "691", continentId: "OC" },
        { name: "Brazil", code: "BR", currency: "Brazilian real", native: "Brasil", phone: "55", continentId: "SA" },
        { name: "Argentina", code: "AR", currency: "Argentine peso", native: "Argentina", phone: "54", continentId: "SA" },
        { name: "Colombia", code: "CO", currency: "Colombian peso", native: "Colombia", phone: "57", continentId: "SA" },
        { name: "Peru", code: "PE", currency: "Peruvian sol", native: "Perú", phone: "51", continentId: "SA" },
        { name: "Venezuela", code: "VE", currency: "Venezuelan bolívar", native: "Venezuela", phone: "58", continentId: "SA" },
        { name: "Chile", code: "CL", currency: "Chilean peso", native: "Chile", phone: "56", continentId: "SA" },
        { name: "Ecuador", code: "EC", currency: "United States dollar", native: "Ecuador", phone: "593", continentId: "SA" },
        { name: "Bolivia", code: "BO", currency: "Bolivian boliviano", native: "Bolivia", phone: "591", continentId: "SA" },
        { name: "Paraguay", code: "PY", currency: "Paraguayan guaraní", native: "Paraguay", phone: "595", continentId: "SA" },
        { name: "Uruguay", code: "UY", currency: "Uruguayan peso", native: "Uruguay", phone: "598", continentId: "SA" }
    ]
}

export const resolvers = {
    Continent: {
        countries: (parent, args, context, info) => {
            return data.countries.filter(country => country.continentId === parent.code)
        },
    },
    Country: {
        languages: (parent, args, context, info) => {
            return data.languages.filter(language => language.countryCodes.includes(parent.code))
        },
    },
    Query: {
        continents: (parent, args, context, info) => {
            return data.continents
        },
        languages: (parent, args, context, info) => {
            return data.languages
        },
        countries: (parent, args, context, info) => {
            return data.countries
        },
    }
}